<?php
/**
 * Created by PhpStorm.
 * User: ПК
 * Date: 28.06.2019
 * Time: 0:26
 */

namespace migrations;


use mvc\model\BaseMigration;

class m270619_190521_Insert extends BaseMigration
{
    public function up()
    {
        $this->executeQuery("INSERT INTO `users`(`displayName`, `email`, `password`, `role`) VALUES ('admin','admin@gmail.com','aa920e61bb9322e341c0d1a3c3668fa8','admin');");
        $this->executeQuery("INSERT INTO `categories`(`id`, `name`, `id_parent_category`) VALUES
(1, \"История\", null),
(2, \"Программирование\", null);");

        $this->executeQuery("INSERT INTO `categories`(`id`, `name`, `id_parent_category`) VALUES
(3, \"Мировая\", 1),
(4, \"Средних веков\", 1),
(5, \"PHP\", 2),
(6, \"JAVA\", 2);");

        $this->executeQuery("INSERT INTO `categories`(`id`, `name`, `id_parent_category`) VALUES
(7, \"Страны\", 4);");

        $this->executeQuery("INSERT INTO `categories`(`id`, `name`, `id_parent_category`) VALUES
(8, \"Украина\", 7),
(9, \"США\", 7);");

        $this->executeQuery("INSERT INTO `authors`(`id`, `name`) VALUES (1, \"Автор 1\"), (2, \"Автор 2\"), (3, \"Автор 3\"), (4, \"Автор 4\"), (5, \"Автор 5\");");

        $this->executeQuery("INSERT INTO `publishers`(`id`, `name`, `address`, `phone`) VALUES (1, \"Издатель 'РАНОК'\", \"Украина, Днепр, Глинки 34\", \"0763961964\"), (2, \"Издатель 'Весенний'\", \"Украина, Харьков, Камчатская 68\", \"0419636913\"), (3, \"Издатель 'Радужный'\", \"Украина, Львов, Зеленая 120\", \"0917530682\"), (4, \"Издатель 123\", \"Украина, Николаев, Козацкая 201\", \"0539710794\"), (5, \"Издатель 1\", \"Украина, Киев, Курчатова 12\", \"0937984861\");");

        $this->executeQuery("INSERT INTO `books`(`id`, `name`, `yearPublisher`, `id_publisher`, `id_category`) VALUES
(1,\"Книга 1\",2014, 1, 5),
(2,\"Книга 2\",2014, 2, 6),
(3,\"Книга 3\",2004, 3, 8),
(4,\"Книга 4\",2007, 5, 9);");


        echo "End migration m270619_190521_Insert <br/>";
    }

    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}